logging:
  level:
    root: info
spring:




  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
#    url: jdbc:postgresql://automotive-project-postgres-1:5432/postgres
    username: ${DATABASE_USER:root}
#    username: postgres
    password: ${DATABASE_PW:1234}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
