logging:
  level:
    root: info
spring:




  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
